%Doctor.Config{
  ignore_modules: [
    Mix.Tasks.Xfood.Import,
    Xfood.Accounts.User,
    Xfood.Accounts.UserToken,
    Xfood.AccountsFixtures,
    Xfood.Application,
    Xfood.Food.Vendor,
    Xfood.Food.VendorQuery,
    Xfood.Mailer,
    Xfood.Reader,
    Xfood.Repo,
    Xfood.Reports.Export,
    Xfood.Time.Parser,
    Xfood.UserFactory,
    XfoodWeb,
    XfoodWeb.Endpoint,
    XfoodWeb.ErrorHTML,
    XfoodWeb.ErrorJSON,
    XfoodWeb.Gettext,
    XfoodWeb.Layouts,
    XfoodWeb.PageController,
    XfoodWeb.PageHTML,
    XfoodWeb.Router,
    XfoodWeb.Telemetry,
    XfoodWeb.UserConfirmationInstructionsLive,
    XfoodWeb.UserConfirmationLive,
    XfoodWeb.UserForgotPasswordLive,
    XfoodWeb.UserLoginLive,
    XfoodWeb.UserRegistrationLive,
    XfoodWeb.UserResetPasswordLive,
    XfoodWeb.UserSessionController,
    XfoodWeb.UserSettingsLive,
    XfoodWeb.VendorLive.FormComponent,
    XfoodWeb.VendorLive.Index,
    XfoodWeb.VendorLive.Show
  ],
  ignore_paths: [],
  min_module_doc_coverage: 40,
  min_module_spec_coverage: 0,
  min_overall_doc_coverage: 50,
  min_overall_moduledoc_coverage: 80,
  min_overall_spec_coverage: 0,
  exception_moduledoc_required: true,
  raise: false,
  reporter: Doctor.Reporters.Full,
  struct_type_spec_required: true,
  umbrella: false,
  failed: false
}
