name: "Cancel PR"

on:
  pull_request:
    types:
      - unlabeled
      - closed

defaults:
  run:
    shell: bash

jobs:
  cancel_previous_builds:
    name: "Cancel previous builds"
    runs-on: ubuntu-latest
    steps:
      - uses: rokroskar/workflow-run-cleanup-action@v0.3.0
    env:
      GITHUB_TOKEN: ${{github.token}}